### ISSUE TITLE
Dismiss button hugs the bottom of the view when displayed in a context without a bottom safe area (iPad, Mac, older iPhones)

### ISSUE THREAD

**Issue by iKenndac** [mergesort/Recap#13]
When displayed in contexts without a bottom safe area, the dismiss button hugs the bottom edge of the view:

<img width="527" alt="image" src="https://github.com/user-attachments/assets/409618f6-6e31-4430-abea-8b38c9b9ca3d">

I had a quick muck around and SwiftUI doesn't appear to be great with this. I _think_ the solution will be pulling that button out of a `ToolbarItem` and placing it in a `VStack` below the tab view, then applying a conditional bit of spacing underneath.

Let me know if you want me to do this.

**Comment by mergesort** [comment]
Fixed in #14, thank you so much @iKenndac!
