### ISSUE TITLE
Dynamic colors in Title and Pager

### ISSUE THREAD

**Issue by massimobio** [mergesort/Recap#21]
Using the basic default implementation it doesn't seem like the Title text and the Pager dots use the correct dynamic colors for night mode.
<img width="559" alt="Screenshot 2024-10-31 at 11 36 43 AM" src="https://github.com/user-attachments/assets/fff41d28-e743-4d09-ae03-9e04a33d5621">

**Comment by mergesort** [comment]
Hey @massimobio, can you share the code that you've written to set the title and page indicator colors? I can't seem to recreate this when using system colors (they seem to change correctly), so I want to make sure I can accommodate your use case.

**Comment by massimobio** [comment]
Hi @mergesort, thanks for the quick reply.
I didn't add any formatting. I was doing an initial test with the examples in the README to see if Recap would work in my app but I'm using it in UIKit which might be the issue?
```Swift
let recapView = RecapScreen(releases: .appReleases)
let hostingController = UIHostingController(rootView: recapView)
splitViewController.present(hostingController, animated: true, completion: nil)
```

adding the formatting you suggested fixes the title coloring 
`RecapScreen(releases: .appReleases).recapScreenTitleStyle(.foreground)` 
but the Pager dots are still the wrong color in dark mode retaining the light mode colors.

I'm not too versed in SwiftUI but I noticed you used Color.black for the recapScreenTitleStyle and SelectedPageIndicatorColorKey, while in the FeatureRow you use the system .primary and .secondary for the text. Might be the issue?

<img width="432" alt="Screenshot 2024-10-31 at 9 56 28 PM" src="https://github.com/user-attachments/assets/6940ac82-69f8-4bd6-ba2b-100944ae0fb7">
<img width="425" alt="Screenshot 2024-10-31 at 9 56 38 PM" src="https://github.com/user-attachments/assets/e521b6c1-ef99-4d4f-8773-1d1e3846d219">

**Comment by mergesort** [comment]
Thank you for sharing the code and providing some good thoughts from your debugging process! You are spot on with your assessment, this was an issue of poorly chosen defaults.

Based on your suggestion, I went ahead and changed the `recapScreenTitleStyle` like this.
```swift
// Before
private struct TitleStyleKey: EnvironmentKey {
    static let defaultValue = AnyShapeStyle(Color.black)
}

// After
private struct TitleStyleKey: EnvironmentKey {
    static let defaultValue = AnyShapeStyle(ForegroundStyle.foreground)
}
```

And updated the default `recapScreenSelectedPageIndicatorColor` like so.
```swift
// Before
private struct SelectedPageIndicatorColorKey: EnvironmentKey {
    static let defaultValue = Color.black
}

// After
private struct SelectedPageIndicatorColorKey: EnvironmentKey {
    static let defaultValue = Color.primary
}
```

This seems to work well in my testing, so I felt confident pushing up a change to the `main` branch. Could I ask you to test and see if that works well for you in your UIKit app? If so, I'll create a new release tomorrow that incorporates these changes.

**Comment by massimobio** [comment]
Yes! It's all good now. Thank you!

**Comment by mergesort** [comment]
Perfect! I've pushed out version [1.1.3](https://github.com/mergesort/Recap/releases/tag/1.1.3), which should have the fix above, based on your suggestions. Thank you so much @massimobio. 🙂
