### ISSUE TITLE
Semantic colors

### ISSUE THREAD

**Issue by massimobio** [mergesort/Recap#22]
Hi @mergesort, I was wondering what you think about adding the [semantic colors](https://developer.apple.com/documentation/swiftui/color#Getting-semantic-colors) `accentColor, primary, secondary` to the list of supported dynamic colors in `Color+SystemNames.swift`.
I wanted to use the sunglasses icon which would look best in black in light mode and in white in dark mode.

**Comment by mergesort** [comment]
I don't see why not, good idea! Here are a couple of screenshots in light and dark mode of the `primary`, `secondary`, and `accentColor`, now available in release [1.1.4](https://github.com/mergesort/Recap/releases/tag/1.1.4).

![System Colors (Light)](https://github.com/user-attachments/assets/75e1f178-1c75-41d7-bd5b-25edd180936d)
![System Colors (Dark)](https://github.com/user-attachments/assets/2aff4c92-2793-4e71-af4d-2fa5a24869b7)

**Comment by massimobio** [comment]
Great, thank you!
