### ISSUE TITLE
Allow system color names to be specified instead of hex values

### ISSUE THREAD

**Issue by jverkoey** [mergesort/Recap#7]
Using the system colors can make for easier light/dark mode handling.

E.g.:

```
- color: systemRed
```

or even just:

```
- color: red
```

**Comment by jverkoey** [comment]
Added an initial PR with some of the thoughts above incorporated!

> Is [this](https://developer.apple.com/documentation/swiftui/color) the complete list of colors we need to support?

Yep! Though I intentionally left out primary/secondary/etc... We might want to add an "accent" option in the future too?

> Is there anything we need to account for given people can create a Color through UIColor or NSColor? I don't think so since we're effectively supporting some predefined constants, but I figured I'd raise it to make sure I didn't overlook anything.

The current PR approach just supports mapping standard system color names to an `ColorName` enum; I could imagine us expanding support for more of the platform-specific colors in the future if that turns out to be useful for folks! As-is I suspect the standard system colors that work across all platforms will be enough for most people.

> Are there any new system colors that were added between iOS 17 and 18, that would need to be accounted for with an availability attribute?

All of the system colors are iOS 15+ so we should be good for minimum OS checking.

**Comment by mergesort** [comment]
Wow, thank you very much @jverkoey! I wasn't expecting a pull request, let alone so quickly. I took a quick look and the approach looks great, I'll request some changes tomorrow but I think we'll be able to get this merged this in pretty quickly. 🙂
